"""Initial migration.

Revision ID: 85eae1da7a4f
Revises: dbe770a6a423
Create Date: 2023-05-21 13:30:29.555613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85eae1da7a4f'
down_revision = 'dbe770a6a423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_product', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
